package com.bubblebob.uto.control;

public enum InputType {
	
	RED_MOVE_UP,RED_MOVE_DOWN,RED_MOVE_RIGHT,RED_MOVE_LEFT,RED_SWITCH_MOVE_MODE,
	GREEN_MOVE_UP,GREEN_MOVE_DOWN,GREEN_MOVE_RIGHT,GREEN_MOVE_LEFT,GREEN_SWITCH_MOVE_MODE,
	RED_BUY_BOAT,RED_BUY_SWITCH,RED_BUY_CANCEL,RED_BUY,RED_SHOW_SCORE,
	GREEN_BUY_BOAT,GREEN_BUY_SWITCH,GREEN_BUY_CANCEL,GREEN_BUY,GREEN_SHOW_SCORE,
	DEBUG_SPAWN_FISH,DEBUG_SPAWN_CLOUD,DEBUG_SPAWN_PIRATE,
	INT_0,INT_1,INT_2,INT_3,INT_4,INT_5,INT_6,INT_7,INT_8,INT_9,
	KEY_ENTER
	;

	
	
	
	
}
