spring:
 main:
  toto: yes #dummy value
  #banner-mode: off
 datasource: 
  url: jdbc:h2:file:D:/tmp/h2/h2base
  driverClassName: org.h2.Driver
  username: dba
  password: dbapass
 jpa:
  database-platform: org.hibernate.dialect.H2Dialect
 h2: 
  console:
   enabled: true
   path: /db
logging:
 level:
  root: WARN

shella:
 webtouch:
  proxy:
   active: false
   host: proxyhost
   port: 3128